apiVersion: v1
kind: Service
metadata:
  name: insurance-predictor
spec:
  selector:
    app: insurance-predictor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer